services:
  forex-user-frontend:
    build: .
    container_name: forex-user-frontend
    ports:
      - "127.0.0.1:80:80"
    restart: always
    networks:
      - web
networks:
  web:
    driver: bridge
    external: true
